<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="25" started-at="2018-08-28T02:36:33Z" finished-at="2018-08-28T02:36:33Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="25" started-at="2018-08-28T02:36:33Z" finished-at="2018-08-28T02:36:33Z">
      <class name="com.guru.login.CreateAccount">
        <test-method status="FAIL" signature="tearUp()[pri:0, instance:com.guru.login.CreateAccount@5f150435]" name="tearUp" is-config="true" duration-ms="0" started-at="2018-08-28T09:36:33Z" finished-at="2018-08-28T09:36:33Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at common.AbstractTest.setUp(AbstractTest.java:20)
	at com.guru.login.CreateAccount.tearUp(CreateAccount.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearUp -->
        <test-method status="SKIP" signature="TC01_CreateAccount()[pri:0, instance:com.guru.login.CreateAccount@5f150435]" name="TC01_CreateAccount" duration-ms="1" started-at="2018-08-28T09:36:33Z" finished-at="2018-08-28T09:36:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC01_CreateAccount -->
        <test-method status="SKIP" signature="tearDown()[pri:0, instance:com.guru.login.CreateAccount@5f150435]" name="tearDown" is-config="true" duration-ms="0" started-at="2018-08-28T09:36:33Z" finished-at="2018-08-28T09:36:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.guru.login.CreateAccount -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
